apiVersion: v1
kind: Service
metadata:
  name: {{ template "helm.name" . }}
  labels:
    app: {{ template "helm.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 8080
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "helm.name" . }}
    release: {{ .Release.Name }}
